# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='nom',
            new_name='name',
        ),
    ]
