# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20160404_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='size',
            field=models.CharField(choices=[('R', 'regular'), ('L', 'large')], default='R', max_length=1),
        ),
    ]
