# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='ingredients',
            field=models.ManyToManyField(related_name='allergies', to='meal.Ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meals', to='meal.Ingredient'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(related_name='menus', to='meal.Ingredient'),
        ),
    ]
