# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='street_number')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('apartment', models.CharField(max_length=10, verbose_name='apartment')),
                ('floor', models.CharField(max_length=3, verbose_name='floor')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postal_code', models.CharField(max_length=6, verbose_name='postal_code')),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.ManyToManyField(related_name='allergic_clients', to='meal.Allergy')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Address', verbose_name='billing_address')),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Home phone', 1), (b'Cell phone', 2), (b'Work phone', 3), (b'Email', 4)], max_length=100, verbose_name='contact_type')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
            ],
            options={
                'verbose_name_plural': 'members',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='client',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='client',
            name='restrictions',
            field=models.ManyToManyField(related_name='restricted_clients', to='meal.Ingredient'),
        ),
        migrations.AddField(
            model_name='address',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member'),
        ),
    ]
