# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160404_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[(0, 'H'), (1, 'F'), (2, 'U')], default=2, max_length=1),
        ),
    ]
