# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[(0, 'H'), (1, 'F'), (2, 'U')], default=1, max_length=1),
        ),
    ]
