# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:28
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_fix004a'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='meal_default_friday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_monday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_saturday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_sunday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_thursday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_tuesday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meal_default_wednesday',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
    ]
