# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20160404_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='member.Member', verbose_name='emergency_contact'),
        ),
    ]
