# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_client_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='apartment'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='allergic_clients', to='meal.Allergy'),
        ),
        migrations.AlterField(
            model_name='client',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='restricted_clients', to='meal.Ingredient'),
        ),
    ]
