# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20160422_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facturation',
            field=models.CharField(choices=[('default', 'default'), ('low income', 'low_income'), ('solidary', 'solidary')], default='default', max_length=10, verbose_name='facturation_type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contact', to='member.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Home phone', 'Home phone'), ('Cell phone', 'Cell phone'), ('Work phone', 'Work phone'), ('Email', 'Email')], max_length=100, verbose_name='contact_type'),
        ),
    ]
