# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20160429_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alert',
            field=models.TextField(blank=True, verbose_name='alert_client'),
        ),
    ]
