# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20160502_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='referencing',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 2), verbose_name='referral_date'),
        ),
    ]
