# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20160502_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='apartment'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='referencing',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 6), verbose_name='referral_date'),
        ),
    ]
