# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_fix241b'),
        ('member', '0012_clientscheduledstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ingredients_to_avoid',
            field=models.ManyToManyField(through='member.Client_avoid_ingredient', to='meal.Ingredient'),
        ),
    ]
