# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_client_components_to_avoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='options',
            field=models.ManyToManyField(through='member.Client_option', to='member.Option'),
        ),
    ]
