# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_fix241b'),
        ('member', '0015_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='restrictions',
            field=models.ManyToManyField(through='member.Restriction', to='meal.Restricted_item'),
        ),
    ]
