# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20160513_1419'),
        ('member', '0015_auto_20160513_2141'),
    ]

    operations = [
    ]
