# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_merge'),
        ('member', '0017_auto_20160519_2039'),
    ]

    operations = [
    ]
