# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_address', to='member.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='referencing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_referent', to='member.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='referencing',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 25), verbose_name='Referral date'),
        ),
    ]
