# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_auto_20160526_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delivery_type',
            field=models.CharField(choices=[('O', 'Ongoing'), ('E', 'Episodic')], default='O', max_length=1),
        ),
    ]
