# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:02
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_auto_20160803_2217'),
        ('member', '0011_client_delivery_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total_amount')),
                ('billing_month', models.IntegerField()),
                ('billing_year', models.IntegerField()),
                ('generation_date', models.DateTimeField(auto_now=True)),
                ('detail', annoying.fields.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_billing', to='billing.Billing')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='order.Order')),
            ],
        ),
    ]
