# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingcycle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingCycle',
            new_name='BillingSummary',
        ),
    ]
