# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 18:31
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.IntegerField()),
                ('detail', annoying.fields.JSONField()),
                ('billing_year', models.IntegerField()),
                ('billing_month', models.IntegerField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
