# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20160803_2217'),
        ('billing', '0004_auto_20160812_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='orders',
            field=models.ManyToManyField(through='billing.OrderBilling', to='order.Order'),
        ),
    ]
