= Sous-Chef Hacknight
Emmanuel Milou <emmanuel.milou@savoirfairelinux.com>
2016-08-25
Mentoring new contributors through contributing their first core commit and growing the community.

:keywords: Django
:page-layout: base
:page-description: {description}
:page-keywords: {keywords}
:icons: font
:toc: right
:experimental:
:mdash: &#8212;
:language: asciidoc
:source-language: {language}
// Refs
:doc-asciidoctor: http://asciidoctor.org/docs/asciidoc-recommended-practices/
:meetup-montrealpython: http://www.meetup.com/Montreal-Python/events/233348153/
:souschef-mailinglist: https://lists.savoirfairelinux.net/mailman/listinfo/sous-chef
:unittest: https://docs.djangoproject.com/en/1.10/topics/testing/overview/

## Venue

This fourth code sprint, or *hackaton*, on Sous-Chef will take place on **Thursday, August 25th, 2016**.

The venue is https://maps.google.com/maps?f=q&hl=en&q=111+Roy+east+Montreal%2C+QC+H2W+1M1%2C+Montr%C3%A9al%2C+QC%2C+ca[Santropol Roulant], in Montréal.

More informations on the {meetup-montrealpython}[Montreal Python Meetup page].

## Agenda

18h:: Welcome!
18h15:: Introduction of the project and the persons involved / discussion, Maison Du Logiciel Libre and Santropol Roulant
18h30-21h30:: Coding

Food will be served.

## Resources

The project is hosted on GitHub: https://github.com/savoirfairelinux/sous-chef

Some useful resources:

* https://www.python.org/dev/peps/pep-0008/[Coding style guide]
* https://travis-ci.org/savoirfairelinux/sous-chef[CI server (Travis)]
* https://waffle.io/savoirfairelinux/sous-chef[Waffle Dashboard]
* https://coveralls.io/github/savoirfairelinux/sous-chef?branch=dev[Coveralls]
* https://help.github.com/articles/creating-a-pull-request/[Creating a Pull Request on GitHub]

## Communication

Please join `#feastproject` on *irc.freenode.net*.

A {souschef-mailinglist}[public mailing-list] is also available. Feel free to subscribe.

## Installation

Please refer to the https://github.com/savoirfairelinux/sous-chef/blob/dev/INSTALL.md[installation procedure].

IMPORTANT: Make sure you already have installed the application before arriving.

## How to contribute

Contributions to an open-source project can take multiple forms:

* Code
* Documentation
* Tests and bug reporting
* Translations

### Code

A pre-requisite is to have Sous-Chef installed on your machine.
Issues of all levels will be available.

The installation procedure is based on Docker and is described https://github.com/savoirfairelinux/sous-chef/blob/dev/INSTALL.md[on GitHub].

#### Issues

Numerous issues are created and waiting for your love on the https://github.com/savoirfairelinux/sous-chef/issues[issue board].

You may also use https://waffle.io/savoirfairelinux/sous-chef[Waffle] as a more *Agile-like* dashboard.

##### Issue trackers

Issues are categorized with the following labels:

* feature
* bug
* i18n (internationalization)
* docs (documentation)
* ux/ui
* tests

##### Issue categories

Besides those trackers, issues are identified regarding the field of expertise:

* python
* frontend
* database

CAUTION: Sous-Chef project is using http://semantic-ui.com/[Semantic UI] as frontend framework.

#### Workflow

* Fork the repository and work from there
* Browse Waffle to pick an issue, change the status to Work-in-Progress and assign it to yourself
* Commit and push your changes into your fork
* When you are done, create a https://github.com/savoirfairelinux/sous-chef/compare[Pull Request] in Feast repository

[IMPORTANT]
====
For your Pull-Request to be merged, it should respect the following:

    * Tests must pass
    * PEP-8 coding style must be respected
    * Code coverage must be complete
    * The branch can be merged automatically
====

https://travis-ci.org/[TravisCI] is configured to run those checks on every Pull-Request. It is recommanded you configure your fork to do the same.

### Documentation

Documentation is important and can always be improved:

* Installation instructions
* Test procedures
* How to help translating the project
* Updating the https://github.com/savoirfairelinux/sous-chef/wiki/TODO[Roadmap]

The preferred markdown syntax is {doc-asciidoctor}[Asciidoc]. Markdown is also accepted.

The https://github.com/savoirfairelinux/sous-chef/wiki/[project wiki] on GitHub could also be used.


### Tests and bug reporting

It could be manual testing and reporting. The GitHub issues can be used to report problems.

Writing unit or functional tests is hightly encouraged and appreciated. Sous-Chef is using {unittest}[unittest] as test framework.

### Translations

Sous-Chef is a bilingual application and needs your talent of translators !

Sous-Chef uses Django multilingual framework, based on Gettext and po files.

Each module has its own set of translation files. To list them all:

 $ find . -name "*.po"

https://poedit.net/[Poedit] can be used to translate those files.
Follow the workflow described in the Code section to contribute your translations.

NOTE: An alternative way to contribute could be to send the po files through emails.

An other way to contribute there is to review the code and make sure all strings are translatable.
