# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20160912_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name'], 'verbose_name_plural': 'Routes'},
        ),
        migrations.AddField(
            model_name='client',
            name='mid',
            field=models.IntegerField(null=True),
        ),
    ]
