# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20161017_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rid',
            field=models.IntegerField(null=True),
        ),
    ]
